# Imagem base Node.js
FROM node:16-alpine

# Diretório de trabalho
WORKDIR /home/consulta-cep

# Copiar o package.json e o package-lock.json
COPY package*.json ./

# Instalar as dependências
RUN npm install --production

# Copiar todo o código fonte para o container
COPY . .

# build the app
RUN npm run build

# Expor a porta 3000 para acesso externo
EXPOSE 3000

# Comando a ser executado ao iniciar o container
CMD ["npm", "start"]
